### PR TITLE
colorama 0.4.6

### PR DESCRIPTION
**Pull request by skupr-anaconda**
**Jira ticket:** [PKG-942](https://anaconda.atlassian.net/browse/PKG-942)

**The upstream data:**
Github releases:  https://github.com/tartley/colorama/releases
[Diff between the latest and previous upstream releases](https://github.com/tartley/colorama/compare/0.4.5...0.4.6)
License: https://github.com/tartley/colorama/blob/master/LICENSE.txt
Changelog: https://github.com/tartley/colorama/blob/master/CHANGELOG.rst
Requirements:
 * pyproject.toml:  https://github.com/tartley/colorama/blob/0.4.6/pyproject.toml

**_Actions:_**

1. Add hatchling to host

**Additional info:**

<details>

**Package's statistics**

<details>

 * Priority C | effort: easy | Category: anaconda | subcategory: dependency | pkg_type: python
 * Outdated platfroms: 'linux-64', 'linux-aarch64', 'linux-s390x', 'linux-ppc64le', 'osx-64', 'osx-arm64', 'win-64'
 * Latest version: 0.4.6
 * Release on PyPi:
    * version: 0.4.6
    * date: 2022-10-25T02:36:22
* [PyPi history](https://pypi.org/project/colorama/#history)
 * Popularity: 
    * 3 months downloads: 2126414.0
    * All time:  15991861 downloads -  colorama  0.4.6  Cross-platform colored terminal text  

</details>

**Other checks:**

<details>

1. - [x] https://github.com/tartley/colorama/tree/0.4.6 exists
3. - [x] Check the pinnings    
7. - [x] `doc_source_url` is present
    https://github.com/tartley/colorama/blob/master/README.rst
8. - [x] Verify that the `build_number` is correct
9. - [x] has `setuptools`
10. - [x] has `wheel`
11. - [x] `pip` in test
12. - [x] Verify the test section
13. - [x] Verify if the package is `architecture specific`
14. - [x] Verify that private modules are not mentioned in the recipe For example: (_private_module)
15.  - [x] license_file: LICENSE.txt is present

16. - [x] license_family BSD is present
17. - [x] License: BSD-3-Clause
    - [x] License is `spdx` compliant
 * Check if the license identifier has correct name from the SPDX License List

| Identifier                           |
|:-------------------------------------|
| BSD-3-Clause                         |
| BSD-3-Clause-Attribution             |
| BSD-3-Clause-Clear                   |
| BSD-3-Clause-LBNL                    |
| BSD-3-Clause-Modification            |
| BSD-3-Clause-No-Military-License     |
| BSD-3-Clause-No-Nuclear-License      |
| BSD-3-Clause-No-Nuclear-License-2014 |
| BSD-3-Clause-No-Nuclear-Warranty     |
| BSD-3-Clause-Open-MPI                |
</details>

**Check dependency issues:**

<details>
../aggregate/colorama-feedstock/recipe/meta.yaml
Dependencies: ['wheel', 'pip', 'python', 'setuptools']

noarch:
- py3.7:  No issues found
- py3.8:  No issues found
- py3.9:  No issues found
- py3.10:  No issues found

linux-64:
- py3.7:  No issues found
- py3.8:  No issues found
- py3.9:  No issues found
- py3.10:  No issues found

linux-ppc64le:
- py3.7:  No issues found
- py3.8:  No issues found
- py3.9:  No issues found
- py3.10:  No issues found

linux-s390x:
- py3.7:  No issues found
- py3.8:  No issues found
- py3.9:  No issues found
- py3.10:  No issues found

osx-64:
- py3.7:  No issues found
- py3.8:  No issues found
- py3.9:  No issues found
- py3.10:  No issues found

osx-arm64:
- py3.8:  No issues found
- py3.9:  No issues found
- py3.10:  No issues found

win-64:
- py3.7:  No issues found
- py3.8:  No issues found
- py3.9:  No issues found
- py3.10:  No issues found

</details>

**Package Build Score: 19**

**Links:**
* [Anaconda Recipes feedstock](https://github.com/AnacondaRecipes/colorama-feedstock)
* [Update branch](https://github.com/AnacondaRecipes/colorama-feedstock/tree/0.4.6)
* [conda-forge recipe](https://github.com/{upstream}/{feedstock_name}-feedstock)
* [PyPI](https://pypi.org/project/colorama)
* [Diff between upstream and feature branch](https://github.com/conda-forge/colorama-feedstock/compare/main...AnacondaRecipes:0.4.6)
* [Diff between origin and feature branch](https://github.com/AnacondaRecipes/colorama-feedstock/compare/master...AnacondaRecipes:0.4.6)
* [The last merged PRs](https://github.com/AnacondaRecipes/colorama-feedstock/pulls?q=is%3Apr+is%3Amerged+sort%3Aupdated-desc+)

</details>

**Updating the recipe:**
If the recipe needs additional modification the update branch can be modified. Note that the PR diffs are not updated with these changes.
```
git clone -b 0.4.6 git@github.com:AnacondaRecipes/colorama-feedstock.git
```

### CODE REVIEW

**Review by psteyer — APPROVED** [review]
LGTM

**Review by varlackc — COMMENTED** [review]
There seems to be a change in the `doc_url` to the following location.

https://pypi.org/project/colorama/

we might want to update to the latest change in the `url`

**Comment by Jrice1317** [comment]
The `doc_url` redirects to https://pypi.org/project/colorama/

**Comment by skupr-anaconda** [comment]
I've fixed doc_url and removed doc_source_url

**Pull request merged**
